### PR TITLE
Add patient identifier documentation

### PR DESCRIPTION
**Pull request by sharlotta93**
https://www.loom.com/share/a087fe85664b4aeea06b363db18a00d4?sid=b0cf8133-9ee0-40de-bfc4-6ec6f4f748b8

### CODE REVIEW

**Comment by danijel** [comment]
This is good, but I think we need to update docs for createPatient and updatePatient mutations. We are recommending patient_code there, and we should switch that to patientIdentifiers

**Comment by danijel** [comment]
Latest changes are https://www.loom.com/share/a087fe85664b4aeea06b363db18a00d4?sid=b0cf8133-9ee0-40de-bfc4-6ec6f4f748b8

**Review by nckhell — APPROVED** [review]

**Comment by belmai** [comment]
@CodiumAI-Agent /review

**Comment by belmai** [comment]
> @CodiumAI-Agent /review

just checking something 😄

**Pull request merged**
